[package]
name = "shared_monday"
version = "0.3.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"
